name: Deploy axon server
on:
  push:
    branches: ["main", "Axon-CICD"]
  pull_request:
    branches: ["main"]
    paths:
      - "k8s/**"
      - "**/deploy-axon-server.yaml"
  workflow_dispatch: 
    branches: ["main"]

jobs:
  pprepare_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::527321763428:role/github-oidc-auth-role
          aws-region: eu-west-1

      - name: configure kubectl
        run: |
          aws eks update-kubeconfig --region eu-west-1 --name miserv-io-eks-cluster
          aws eks get-token
          kubectl cluster-info


      