name: Deploy axon server
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    paths:
      - "k8s/**"
      - "**/deploy-axon-server.yaml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: